# balatro_gym/jokers.py
from dataclasses import dataclass
from typing import List

@dataclass(frozen=True)
class JokerInfo:
    id: int
    name: str
    base_cost: int   # 0 ⇒ legendary / shop-ineligible
    effect: str
JOKER_LIBRARY: List[JokerInfo] = [
    JokerInfo(  1,"Joker",2,"+4 Mult"),
    JokerInfo(  2,"Greedy Joker",5,"♦ +3 Mult"),
    JokerInfo(  3,"Lusty Joker",5,"♥ +3 Mult"),
    JokerInfo(  4,"Wrathful Joker",5,"♠ +3 Mult"),
    JokerInfo(  5,"Gluttonous Joker",5,"♣ +3 Mult"),
    JokerInfo(  6,"Jolly Joker",3,"+8 Mult if Pair"),
    JokerInfo(  7,"Zany Joker",4,"+12 Mult if Trips"),
    JokerInfo(  8,"Mad Joker",4,"+10 Mult if Two Pair"),
    JokerInfo(  9,"Crazy Joker",4,"+12 Mult if Straight"),
    JokerInfo( 10,"Droll Joker",4,"+10 Mult if Flush"),
    JokerInfo( 11,"Sly Joker",3,"+50 Chips if Pair"),
    JokerInfo( 12,"Wily Joker",4,"+100 Chips if Trips"),
    JokerInfo( 13,"Clever Joker",4,"+80 Chips if Two Pair"),
    JokerInfo( 14,"Devious Joker",4,"+100 Chips if Straight"),
    JokerInfo( 15,"Crafty Joker",4,"+80 Chips if Flush"),
    JokerInfo( 16,"Half Joker",5,"+20 Mult ≤3 cards"),
    JokerInfo( 17,"Joker Stencil",8,"×1 Mult per empty slot"),
    JokerInfo( 18,"Four Fingers",7,"Flush/Straight size 4"),
    JokerInfo( 19,"Mime",5,"Retrigger held abilities"),
    JokerInfo( 20,"Credit Card",1,"Debt to −$20"),
    JokerInfo( 21,"Ceremonial Dagger",6,"Sacrifice joker for Mult"),
    JokerInfo( 22,"Banner",5,"+30 Chips/discard left"),
    JokerInfo( 23,"Mystic Summit",5,"+15 Mult at 0 discards"),
    JokerInfo( 24,"Marble Joker",6,"Add Stone on blind"),
    JokerInfo( 25,"Loyalty Card",5,"×4 every 6 hands"),
    JokerInfo( 26,"8 Ball",5,"¼ Tarot chance on 8"),
    JokerInfo( 27,"Misprint",4,"+0–23 Mult"),
    JokerInfo( 28,"Dusk",5,"Retrigger final hand"),
    JokerInfo( 29,"Raised Fist",5,"2× lowest rank Mult"),
    JokerInfo( 30,"Chaos the Clown",4,"Free reroll / shop"),
    JokerInfo( 31,"Fibonacci",8,"+8 Mult on A,2,3,5,8"),
    JokerInfo( 32,"Steel Joker",7,"×0.2 Mult per Steel"),
    JokerInfo( 33,"Scary Face",4,"+30 Chips per face"),
    JokerInfo( 34,"Abstract Joker",4,"+3 Mult per joker"),
    JokerInfo( 35,"Delayed Grat.",4,"$2/discard if none"),
    JokerInfo( 36,"Hack",6,"Retrigger 2-5"),
    JokerInfo( 37,"Pareidolia",5,"All cards → face"),
    JokerInfo( 38,"Gros Michel",5,"+15 Mult; 1/6 break"),
    JokerInfo( 39,"Even Steven",4,"+4 Mult even ranks"),
    JokerInfo( 40,"Odd Todd",4,"+31 Chips odd ranks"),
    JokerInfo( 41,"Scholar",4,"+20 Chips +4 Mult/A"),
    JokerInfo( 42,"Business Card",4,"Face ½ chance $2"),
    JokerInfo( 43,"Supernova",5,"+plays to Mult"),
    JokerInfo( 44,"Ride the Bus",6,"+1 Mult no-face streak"),
    JokerInfo( 45,"Space Joker",5,"¼ upgrade hand lvl"),
    JokerInfo( 46,"Egg",4,"+$3 sell/round"),
    JokerInfo( 47,"Burglar",6,"+3 hands; lose discards"),
    JokerInfo( 48,"Blackboard",6,"×3 if only ♠♣"),
    JokerInfo( 49,"Runner",5,"+15 Chips if Straight"),
    JokerInfo( 50,"Ice Cream",5,"+100 −5 Chips/hand"),
    JokerInfo( 51,"DNA",8,"Clone 1-card first"),
    JokerInfo( 52,"Splash",3,"Every card scores"),
    JokerInfo( 53,"Blue Joker",5,"+2 Chips / deck card"),
    JokerInfo( 54,"Sixth Sense",6,"Single 6 → Spectral"),
    JokerInfo( 55,"Constellation",6,"+0.1× per Planet"),
    JokerInfo( 56,"Hiker",5,"+5 Chips permanent"),
    JokerInfo( 57,"Faceless Joker",4,"+$5 3 face discard"),
    JokerInfo( 58,"Green Joker",4,"+1 Mult/hand −1 discard"),
    JokerInfo( 59,"Superposition",4,"Tarot if Ace+Straight"),
    JokerInfo( 60,"To Do List",4,"$4 if target hand"),
    JokerInfo( 61,"Cavendish",4,"×3; 1/1000 destroy"),
    JokerInfo( 62,"Card Sharp",6,"×3 if repeat hand"),
    JokerInfo( 63,"Red Card",5,"+3 Mult / pack skip"),
    JokerInfo( 64,"Madness",7,"×0.5 Mult, destroys"),
    JokerInfo( 65,"Square Joker",4,"+4 Chips 4-card"),
    JokerInfo( 66,"Séance",6,"Straight-Flush → Spectral"),
    JokerInfo( 67,"Riff-Raff",6,"2 jokers on blind"),
    JokerInfo( 68,"Vampire",7,"+0.1× per Enhanced"),
    JokerInfo( 69,"Shortcut",7,"Gapped straights"),
    JokerInfo( 70,"Hologram",7,"+0.25× per card added"),
    JokerInfo( 71,"Vagabond",8,"Tarot if hand ≤ $4"),
    JokerInfo( 72,"Baron",8,"×1.5 per King"),
    JokerInfo( 73,"Cloud 9",7,"$ per 9 in deck"),
    JokerInfo( 74,"Rocket",6,"$ each round +2 boss"),
    JokerInfo( 75,"Obelisk",8,"+0.2× avoid top hand"),
    JokerInfo( 76,"Midas Mask",7,"Face → Gold"),
    JokerInfo( 77,"Luchador",5,"Sell disables boss"),
    JokerInfo( 78,"Photograph",5,"First face ×2"),
    JokerInfo( 79,"Gift Card",6,"+$1 sell value all"),
    JokerInfo( 80,"Turtle Bean",6,"+5 hand −1/round"),
    JokerInfo( 81,"Erosion",6,"+4 Mult per card below"),
    JokerInfo( 82,"Reserved Parking",6,"Face $1 ½ chance"),
    JokerInfo( 83,"Mail-In Rebate",4,"$5 per rank discard"),
    JokerInfo( 84,"To the Moon",5,"Extra interest"),
    JokerInfo( 85,"Hallucination",4,"½ Tarot on pack"),
    JokerInfo( 86,"Fortune Teller",6,"+1 Mult per Tarot"),
    JokerInfo( 87,"Juggler",4,"+1 hand size"),
    JokerInfo( 88,"Drunkard",4,"+1 discard / round"),
    JokerInfo( 89,"Stone Joker",6,"+25 Chips per Stone"),
    JokerInfo( 90,"Golden Joker",6,"+$4 each round"),
    JokerInfo( 91,"Lucky Cat",6,"+0.25× per lucky"),
    JokerInfo( 92,"Baseball Card",8,"Uncommons ×1.5"),
    JokerInfo( 93,"Bull",6,"+2 Chips per $5"),
    JokerInfo( 94,"Diet Cola",6,"Sell → Double Tag"),
    JokerInfo( 95,"Trading Card",6,"Discard 1 → $3"),
    JokerInfo( 96,"Flash Card",5,"+2 Mult per reroll"),
    JokerInfo( 97,"Popcorn",5,"+20 Mult −4/round"),
    JokerInfo( 98,"Spare Trousers",6,"+2 Mult if Two Pair"),
    JokerInfo( 99,"Ancient Joker",8,"×1.5 per suit"),
    JokerInfo(100,"Ramen",6,"×2 Mult −0.01/disc"),
    JokerInfo(101,"Walkie Talkie",4,"+10 Chips +4 Mult 10/4"),
    JokerInfo(102,"Seltzer",6,"Retrigger next 10 hands"),
    JokerInfo(103,"Castle",6,"+3 Chips per suit disc"),
    JokerInfo(104,"Smiley Face",4,"+5 Mult per face"),
    JokerInfo(105,"Campfire",9,"+0.25× per card sold"),
    JokerInfo(106,"Golden Ticket",5,"+$4 per Gold scored"),
    JokerInfo(107,"Mr. Bones",5,"Prevent death at 25%"),
    JokerInfo(108,"Acrobat",6,"×3 final hand"),
    JokerInfo(109,"Sock & Buskin",6,"Retrigger face cards"),
    JokerInfo(110,"Swashbuckler",4,"+Mult = sell values"),
    JokerInfo(111,"Troubadour",6,"+2 hand −1/round"),
    JokerInfo(112,"Certificate",6,"Start with sealed card"),
    JokerInfo(113,"Smeared Joker",7,"♥♦ same, ♠♣ same"),
    JokerInfo(114,"Throwback",6,"+0.25× per blind skip"),
    JokerInfo(115,"Hanging Chad",4,"Retrigger first card ×2"),
    JokerInfo(116,"Rough Gem",7,"+$1 per ♦ scored"),
    JokerInfo(117,"Bloodstone",7,"50% ×1.5 ♥"),
    JokerInfo(118,"Arrowhead",7,"+50 Chips per ♠"),
    JokerInfo(119,"Onyx Agate",7,"+7 Mult per ♣"),
    JokerInfo(120,"Glass Joker",6,"+0.75× per Glass"),
    JokerInfo(121,"Showman",5,"Dup consumables"),
    JokerInfo(122,"Flower Pot",6,"×3 if all suits"),
    JokerInfo(123,"Blueprint",10,"Copy right Joker"),
    JokerInfo(124,"Wee Joker",8,"+8 Chips per 2"),
    JokerInfo(125,"Merry Andy",7,"+3 discards −1 hand"),
    JokerInfo(126,"Oops! All 6s",4,"Double probabilities"),
    JokerInfo(127,"The Idol",6,"×2 target rank/suit"),
    JokerInfo(128,"Seeing Double",6,"×2 if ♣ + any suit"),
    JokerInfo(129,"Matador",7,"+$8 on boss trigger"),
    JokerInfo(130,"Hit the Road",8,"+0.5× per Jack disc"),
    JokerInfo(131,"The Duo",8,"×2 if Pair"),
    JokerInfo(132,"The Trio",8,"×3 if Trips"),
    JokerInfo(133,"The Family",8,"×4 if Quads"),
    JokerInfo(134,"The Order",8,"×3 if Straight"),
    JokerInfo(135,"The Tribe",8,"×2 if Flush"),
    JokerInfo(136,"Stuntman",7,"+250 Chips −2 hand"),
    JokerInfo(137,"Invisible Joker",8,"Duplicate after 2"),
    JokerInfo(138,"Brainstorm",10,"Copy left Joker"),
    JokerInfo(139,"Satellite",6,"$ per Planet used"),
    JokerInfo(140,"Shoot the Moon",5,"+13 Mult per Queen"),
    JokerInfo(141,"Driver's License",7,"×3 if 16 Enhanced"),
    JokerInfo(142,"Cartomancer",6,"Tarot on blind"),
    JokerInfo(143,"Astronomer",8,"Planet cards free"),
    JokerInfo(144,"Burnt Joker",8,"Upgrade first discard"),
    JokerInfo(145,"Bootstraps",7,"+2 Mult per $5"),
    JokerInfo(146,"Canio",0,"+1× per face destroyed"),
    JokerInfo(147,"Triboulet",0,"Kings & Queens ×2"),
    JokerInfo(148,"Yorick",0,"+1× per 23 discards"),
    JokerInfo(149,"Chicot",0,"Disable every boss"),
    JokerInfo(150,"Perkeo",0,"Negative copy consumable"),
]
